### ISSUE TITLE
fonts: add support for cyrillic symbols

### ISSUE THREAD

**Issue by Lichery** [shagu/pfUI#732]
# BigNoodleTitling font
[BigNoodleTitling.zip](https://github.com/shagu/pfUI/files/1426512/BigNoodleTitling.zip)
Before (your current version):
(https://user-images.githubusercontent.com/24303693/32149893-90635300-bd1c-11e7-97d0-74dbd855c998.jpg)
After:
(https://user-images.githubusercontent.com/24303693/32162048-ac8b0608-bd68-11e7-9f91-5aea9723b9da.jpg)
Proof of working capacity of a font:
(https://user-images.githubusercontent.com/24303693/32161951-65d384a6-bd68-11e7-9965-503dbaec72bc.jpg)

# DieDieDie font
HOORAY!!! I was able to fix the font [DieDieDie.zip](https://github.com/shagu/pfUI/files/1425566/DieDieDie.zip).
Before (your current version):
(https://user-images.githubusercontent.com/24303693/32149398-f1759f7a-bd14-11e7-8556-26dd123a6283.jpg)
After:
(https://user-images.githubusercontent.com/24303693/32149409-124b9df8-bd15-11e7-818b-fb42a9ea7f60.jpg)
Proof of working capacity of a font:
(https://user-images.githubusercontent.com/24303693/32149413-28bedbea-bd15-11e7-83f3-fa1852ba1a2d.jpg)

# Continuum font
[Continuum.zip](https://github.com/shagu/pfUI/files/1425590/Continuum.zip)
Before (your current version):
(https://user-images.githubusercontent.com/24303693/32149747-563098b6-bd1a-11e7-82b0-f1ff730903a4.jpg)
After:
(https://user-images.githubusercontent.com/24303693/32149749-5bd389a4-bd1a-11e7-8c46-3a8628b4d341.jpg)
Proof of working capacity of a font:
(https://user-images.githubusercontent.com/24303693/32149743-491e70a8-bd1a-11e7-99da-0a0a6ef8987f.jpg)

# MyriadPro-BoldCond font
[MyriadPro-BoldCond.zip](https://github.com/shagu/pfUI/files/1427057/MyriadPro-BoldCond.zip)
I propose to replace the current Myriad-Pro font with MyriadPro-BoldCond.
I downloaded it from [here](http://abali.ru/shrift-myriadpro-skachat/) and did not edit anything in it. I compared the tables of symbols and this font, which I suggest there is much more characters:
(https://user-images.githubusercontent.com/24303693/32169438-814ad8c4-bd81-11e7-91b5-ef4717df7727.jpg)
as you can see, there are a lot of symbols used in French, German and other languages. You see red names - this means that there is already a symbol with the same unicode name. In my font many symbols have corrected these names.

# _________________________________________________________
P.S. You may wonder why I do all this. I do this because I believe that fonts should be universal and publicly available and everyone could use all the fonts in the addon, rather than look for a replacement on the Internet or use additional addons.

**Comment by Road-block** [comment]
You did receive an answer 😄 
Make a small plugin for pfUI to load your fonts following this example:  
https://github.com/shagu/pfUI-font-roboto

**Comment by Lichery** [comment]
why use some kind of plug-in to use the standard addon font? Why not just update the font to the one I suggested? He supports both Cyrillic and Latin symbols.
Shagu wrote: " I don't want to break any other languages by replacing a font with an unknown version."
what other languages?

**Comment by Lichery** [comment]
looked at the character table in the current font, it does not support hieroglyphs. So what other languages can be broken?

I even compared these two tables (current and my) fonts and in my font lacks only a few characters that will not be used anywhere. In addition, in my version there are several characters that are missing in the current:
![bandicam 2017-10-28 18-56-09-718](https://user-images.githubusercontent.com/24303693/32136089-0fd94182-bc12-11e7-8bcc-51542b1013e3.jpg)

**Comment by shagu** [comment]
> what other languages?

For example:
* German (ü,ä,ö,ß,...)
* French (ê,é,è)

If you can provide me a font which is identical to the old one plus cyrillic letters, I'm totally fine merging it ;)

**Comment by Lichery** [comment]
the symbols you listed are present in my font. Look at the table of symbols in the FontLab. 
Okay, I'll transfer these few missing characters so that the fonts are identical)

**Comment by Lichery** [comment]
Done [BigNoodleTitling_mixed.zip](https://github.com/shagu/pfUI/files/1425341/BigNoodleTitling_mixed.zip) :)
Green highlighting this is characters that were missing in my font
![bandicam 2017-10-29 20-15-10-765](https://user-images.githubusercontent.com/24303693/32146306-39b553d6-bce6-11e7-8313-1a1cb0db7f75.jpg)

**Comment by Lichery** [comment]
Why two lines of Cyrillic and Latin characters do not I know, but it was exactly the same for your and my font, before they merged

**Comment by Lichery** [comment]
I understood ... one row for uppercase, and one for lowercase symbols. In this font all symbols are uppercase and therefore we have two rows of identical symbols.

**Comment by shagu** [comment]
Which tool did you've used for the latest screenshot?

I made a quick review and it seems like your new font is still missing some entries which were existent in the old font:
[1](https://i.imgur.com/wgnhPwnr.png)
left: new font, right: old font

I also created a merged version of the font, but I wasn't able to find any tooling to easilly `diff` two truetype fonts. :(

**Comment by Lichery** [comment]
I'm using a program FontLab Studio 5.2.2

**Comment by Lichery** [comment]
These two characters are the same as 017D. Manually I can not completely transfer them. I transfer them, but I can not give them the same name as in your original font. To merge fonts, I used the program function: FontLab Studio 5.2.2 -> Tools -> Merge Fonts... and set parameter "Do not copy source glyph".

Even the program could not transfer these two characters. I believe that they are superfluous because as I wrote above this symbol is numbered 017D and has the same name "Zcaron"

**Comment by Lichery** [comment]
HOORAY!!! I was able to fix the font [DieDieDie.zip](https://github.com/shagu/pfUI/files/1425566/DieDieDie.zip).
Before (your current version):
![bandicam 2017-10-30 01-47-22-201](https://user-images.githubusercontent.com/24303693/32149398-f1759f7a-bd14-11e7-8556-26dd123a6283.jpg)
After:
![bandicam 2017-10-30 01-47-37-766](https://user-images.githubusercontent.com/24303693/32149409-124b9df8-bd15-11e7-818b-fb42a9ea7f60.jpg)

Proof of working capacity of a font:
![wow 2017-10-30 01-48-46-123](https://user-images.githubusercontent.com/24303693/32149413-28bedbea-bd15-11e7-83f3-fa1852ba1a2d.jpg)

Please add DieDieDie and BigNoodleTitling in addon. :)

**Comment by Lichery** [comment]
[Continuum.zip](https://github.com/shagu/pfUI/files/1425590/Continuum.zip)
Before (your current version):
![bandicam 2017-10-30 02-26-38-608](https://user-images.githubusercontent.com/24303693/32149747-563098b6-bd1a-11e7-82b0-f1ff730903a4.jpg)
After:
![bandicam 2017-10-30 02-26-25-208](https://user-images.githubusercontent.com/24303693/32149749-5bd389a4-bd1a-11e7-8c46-3a8628b4d341.jpg)
Proof of working capacity of a font:
![wow 2017-10-30 02-28-08-735](https://user-images.githubusercontent.com/24303693/32149743-491e70a8-bd1a-11e7-99da-0a0a6ef8987f.jpg)

**Comment by Lichery** [comment]
I cleaned the report of unnecessary messages that everything was neat. I transferred the necessary data to the first message.

**Comment by Lichery** [comment]
About the font BigNoodleTitling. I altered it, now it is completely identical to the fact that you have + Cyrillic symbols. Look.

**Comment by shagu** [comment]
Thank you, looks very good, except for `MyriadPro-BoldCond`. I don't know if WoW supports `.otf` files and I'm not sure if WoW will handle `bold` and `condensed` flags properly. I'll better stick to the old one there.

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/1443c120cc8d99e4ec0f5d2fe31a5cce7595825f

**Comment by Lichery** [comment]
thanks :)
